"macro DXExport(",
" object",
",base_name",
") -> (",
" file_written",
") {",
"DXExport_Inp7_o1 = object;",
"DXExport_Inp8_o1 = base_name;",
"Export(",
"DXExport_Inp7_o1,",
"DXExport_Inp8_o1,",
"\"dx text follows\"",
") [instance: 1, cache: 1];",
"DXExport_Format_8_o1[cache: 2] = ",
"Format(",
"\"%s.dx\",",
"DXExport_Inp8_o1,",
"NULL",
") [instance: 8, cache: 1];",
"file_written = DXExport_Format_8_o1;",
"}",
NULL
