/***********************************************************************/
/* Open Visualization Data Explorer                                    */
/* (C) Copyright IBM Corp. 1989,1999                                   */
/* ALL RIGHTS RESERVED                                                 */
/* This code licensed under the                                        */
/*    (char *)"IBM PUBLIC LICENSE - Open Visualization Data Explorer" */
/***********************************************************************/

#ifndef _EWDefaultResources_h
#define _EWDefaultResources_h

#if !defined( DX_NEW_KEYLAYOUT )

String EditorWindow::DefaultResources[] = {
    (char *)".title:                                      Visual Program "
            "Editor",
    (char *)".iconName:                                   VPE",
    (char *)".minWidth:                                   480",
    (char *)".minHeight:                                  400",
    (char *)"*workArea.width:                             850",
    (char *)"*workArea.height:                            650",
    (char *)"*notebook.width:                   			    "
            "180",
    (char *)"*scrolledWindow*XmScrollBar.initialDelay:    2000",
    (char *)"*scrolledWindow*XmScrollBar.repeatDelay:     2000",
    (char *)"*fileMenu.labelString:                       File",
    (char *)"*fileMenu.mnemonic:                          F",
    (char *)"*vpeNewOption.labelString:                   New",
    (char *)"*vpeNewOption.mnemonic:                      N",
    (char *)"*vpeOpenOption.labelString:                  Open Program...",
    (char *)"*vpeOpenOption.mnemonic:                     O",
    (char *)"*vpeSaveOption.labelString:                  Save Program",
    (char *)"*vpeSaveOption.mnemonic:                     S",
    (char *)"*vpeSaveOption.accelerator:                  Ctrl<Key>S",
    (char *)"*vpeSaveOption.acceleratorText:              Ctrl+S",
    (char *)"*vpeSaveMacroOption.labelString:             Save Macro",
    (char *)"*vpeSaveMacroOption.mnemonic:                S",
    (char *)"*vpeSaveMacroOption.accelerator:             Ctrl<Key>S",
    (char *)"*vpeSaveMacroOption.acceleratorText:         Ctrl+S",
    (char *)"*vpeSaveAsOption.labelString:                Save Program As...",
    (char *)"*vpeSaveMacroAsOption.labelString:           Save Macro As...",
    (char *)"*vpeSettingsCascade.labelString: 		        Program "
            "Settings",
    (char *)"*vpeSettingsCascade.mnemonic: 		            r",
    (char *)"*vpeSaveCfgOption.labelString:               Save As...",
    (char *)"*vpeSaveCfgOption.mnemonic:                  S",
    (char *)"*vpeOpenCfgOption.labelString:               Load...",
    (char *)"*vpeOpenCfgOption.mnemonic:                  L",
    (char *)"*vpeSaveAsOption.mnemonic:                   a",
    (char *)"*vpePrintProgramOption.labelString:          Print Program...",
    (char *)"*vpePrintProgramOption.mnemonic:             P",
    (char *)"*vpeLoadMDFOption.labelString:               Load Module "
            "Description(s)...",
    (char *)"*vpeLoadMDFOption.mnemonic:                  M",
    (char *)"*vpeLoadMacroOption.labelString:             Load Macro...",
    (char *)"*vpeLoadMacroOption.mnemonic:                L",
#ifdef DXUI_DEVKIT
    (char *)"*vpeSaveAsCCodeOption.labelString:           Save As C Code...",
    (char *)"*vpeSaveAsCCodeOption.mnemonic:              v",
#endif /* DXUI_DEVKIT */
    (char *)"*vpeCloseOption.labelString:                 Close",
    (char *)"*vpeCloseOption.mnemonic:                    C",
    (char *)"*vpeCloseOption.accelerator:                 Ctrl<Key>Q",
    (char *)"*vpeCloseOption.acceleratorText:             Ctrl+Q",
    (char *)"*editMenu.labelString:                       Edit",
    (char *)"*editMenu.mnemonic:                          E",
    (char *)"*vpeUndoOption.labelString:                  Undo",
    (char *)"*vpeUndoOption.accelerator:                  Ctrl<Key>U",
    (char *)"*vpeUndoOption.acceleratorText:              Ctrl+U",
    (char *)"*vpeValuesOption.labelString:                Configuration...",
    (char *)"*vpeValuesOption.mnemonic:                   C",
    (char *)"*vpeValuesOption.accelerator:                Ctrl<Key>F",
    (char *)"*vpeValuesOption.acceleratorText:            Ctrl+F",
    (char *)"*vpeFindToolOption.labelString:              Find Tool...",
    (char *)"*vpeFindToolOption.mnemonic:                 F",
    (char *)"*vpeEditTabsCascade.labelString: 		        Input/Output "
            "Tabs",
    (char *)"*vpeEditTabsCascade.mnemonic: 		            T",
    (char *)"*vpeAddInputTabOption.labelString:           Add Input Tab",
    (char *)"*vpeAddInputTabOption.mnemonic:              A",
    (char *)"*vpeAddInputTabOption.accelerator:           Ctrl<Key>A",
    (char *)"*vpeAddInputTabOption.acceleratorText:       Ctrl+A",
    (char *)"*vpeRemoveInputTabOption.labelString:        Remove Input Tab",
    (char *)"*vpeRemoveInputTabOption.mnemonic:           R",
    (char *)"*vpeRemoveInputTabOption.accelerator:        Ctrl<Key>R",
    (char *)"*vpeRemoveInputTabOption.acceleratorText:    Ctrl+R",
    (char *)"*vpeAddOutputTabOption.labelString:          Add Output Tab",
    (char *)"*vpeAddOutputTabOption.mnemonic:             O",
    (char *)"*vpeRemoveOutputTabOption.labelString:       Remove Output Tab",
    (char *)"*vpeRemoveOutputTabOption.mnemonic:          T",
    (char *)"*vpeHideAllTabsOption.labelString:           Hide All Tabs",
    (char *)"*vpeHideAllTabsOption.mnemonic:              H",
    (char *)"*vpeHideAllTabsOption.accelerator:           Ctrl<Key>H",
    (char *)"*vpeHideAllTabsOption.acceleratorText:       Ctrl+H",
    (char *)"*vpeRevealAllTabsOption.labelString:         Reveal All Tabs",
    (char *)"*vpeRevealAllTabsOption.mnemonic:            L",
    (char *)"*vpeRevealAllTabsOption.accelerator:         Ctrl<Key>L",
    (char *)"*vpeRevealAllTabsOption.acceleratorText:     Ctrl+L",
    (char *)"*vpeEditSelectCascade.labelString:		        "
            "Select/Deselect Tools",
    (char *)"*vpeEditSelectCascade.mnemonic:		          S",

#ifndef FORGET_GETSET
    (char *)"*programVerifyCascade.labelString:		  Assign Get/Set Scope",
    (char *)"*programVerifyCascade.mnemonic:		  V",
    (char *)"*getSetConversion.labelString:		  Convert All "
            "Modules...",
    (char *)"*getSetConversion.mnemonic:		  C",
    (char *)"*setToGlobal.labelString:		     	  Set Selected "
            "Gets/Sets Global",
    (char *)"*setToGlobal.mnemonic:		     	  G",
    (char *)"*setToLocal.labelString:		          Set Selected "
            "Gets/Sets Local",
    (char *)"*setToLocal.mnemonic:		       	  L",
#endif
    (char *)"*vpeSelectAllOption.labelString:                Select All",
    (char *)"*vpeSelectAllOption.mnemonic:                   S",
    (char *)"*vpeSelectConnectedOption.labelString:          Select Connected",
    (char *)"*vpeSelectConnectedOption.mnemonic:             C",
    (char *)"*vpeSelectUnconnectedOption.labelString:        Select "
            "Unconnected",
    (char *)"*vpeSelectUnconnectedOption.mnemonic:           U",
    (char *)"*vpeSelectUpwardOption.labelString:             Select Upward",
    (char *)"*vpeSelectUpwardOption.mnemonic:                p",
    (char *)"*vpeSelectDownwardOption.labelString:           Select Downward",
    (char *)"*vpeSelectDownwardOption.mnemonic:              D",
    (char *)"*vpeDeselectAllOption.labelString:              Deselect All",
    (char *)"*vpeDeselectAllOption.mnemonic:                 e",
    (char *)"*vpeSelectUnselectedOption.labelString:         Select Unselected",
    (char *)"*vpeSelectUnselectedOption.mnemonic:            n",
    (char *)"*vpeOutputCacheabilityCascade.labelString:      Output "
            "Cacheability",
    (char *)"*vpeOutputCacheabilityCascade.mnemonic:         u",
    (char *)"*vpeOptimizeCacheability.labelString:           Optimize "
            "Cacheability",
    (char *)"*vpeOptimizeCacheability.mnemonic:              O",
    (char *)"*vpeEditOutputCacheabilityCascade.labelString:  Set Output "
            "Cacheability",
    (char *)"*vpeEditOutputCacheabilityCascade.mnemonic:     S",
    (char *)"*vpeCacheAllOutputsOption.labelString:          Cache All Results",
    (char *)"*vpeCacheAllOutputsOption.mnemonic:             A",
    (char *)"*vpeCacheLastOutputsOption.labelString:         Cache Last Result",
    (char *)"*vpeCacheLastOutputsOption.mnemonic:            L",
    (char *)"*vpeCacheNoOutputsOption.labelString:           Cache No Results",
    (char *)"*vpeCacheNoOutputsOption.mnemonic:              N",
    (char *)"*vpeShowOutputCacheabilityCascade.labelString:  Show Output "
            "Cacheability",
    (char *)"*vpeShowOutputCacheabilityCascade.mnemonic:     h",
    (char *)"*vpeShowCacheAllOutputsOption.labelString:      All Results",
    (char *)"*vpeShowCacheAllOutputsOption.mnemonic:         A",
    (char *)"*vpeShowCacheLastOutputsOption.labelString:     Last Result",
    (char *)"*vpeShowCacheLastOutputsOption.mnemonic:        L",
    (char *)"*vpeShowCacheNoOutputsOption.labelString:       No Results",
    (char *)"*vpeShowCacheNoOutputsOption.mnemonic:          N",
    (char *)"*vpeCutOption.labelString:                      Cut",
    (char *)"*vpeCutOption.mnemonic:                         t",
    (char *)"*vpeCutOption.acceleratorText:                  Delete",
    (char *)"*vpeCutOption.accelerator:                      <Key>osfDelete",
    (char *)"*vpeCopyOption.labelString:                     Copy",
    (char *)"*vpeCopyOption.mnemonic:                        p",
    (char *)"*vpeCopyOption.acceleratorText:                 Shift+Delete",
    (char *)"*vpeCopyOption.accelerator:                     "
            "Shift<Key>osfDelete",
    (char *)"*vpePasteOption.labelString:                    Paste",
    (char *)"*vpePasteOption.mnemonic:                       e",
    (char *)"*vpePasteOption.acceleratorText:                Shift+Ins",
    (char *)"*vpePasteOption.accelerator:                    "
            "Shift<Key>osfInsert",
    (char *)"*vpeDeleteOption.labelString:                   Delete",
    (char *)"*vpeDeleteOption.mnemonic:                      D",
    (char *)"*vpeDeleteOption.acceleratorText:               Ctrl+Delete",
    (char *)"*vpeDeleteOption.accelerator:                   "
            "Ctrl<Key>osfDelete",

#ifdef aviion
    (char *)"*vpeCutOption.accelerator:                      <Key>Delete",
    (char *)"*vpeCopyOption.accelerator:                     Shift<Key>Delete",
    (char *)"*vpePasteOption.accelerator:                    Shift<Key>Insert",
    (char *)"*vpeDeleteOption.accelerator:                   Ctrl<Key>Delete",
#endif
    (char *)"*vpeAddDecorator.labelString:                Add Annotation",
    (char *)"*vpeAddDecorator.mnemonic:                   T",
    (char *)"*vpeInsertNetOption.labelString:             Insert Visual "
            "Program...",
    (char *)"*vpeInsertNetOption.mnemonic:                I",
    (char *)"*vpeCreateMacroOption.labelString:           Create Macro...",
    (char *)"*vpeCreateMacroOption.mnemonic:              M",
    (char *)"*vpePageCascade.labelString:                 Page",
    (char *)"*vpeCreatePageOption.labelString:            Create Empty Page",
    (char *)"*vpeCreatePageOption.mnemonic:               E",
    (char *)"*vpeSelectedPageOption.labelString:          Create with Selected "
            "Tools",
    (char *)"*vpeSelectedPageOption.mnemonic:             C",
    (char *)"*vpeMoveToPageOption.labelString:            Move Selected "
            "Tools...",
    (char *)"*vpeMoveToPageOption.mnemonic:               M",
    (char *)"*vpeChopPageOption.labelString:          	  Separate Selected "
            "Tools",
    (char *)"*vpeChopPageOption.mnemonic:          	  S",
    (char *)"*vpeFusePageOption.labelString:          	  Reconnect Selected "
            "Tools",
    (char *)"*vpeFusePageOption.mnemonic:          	  R",
    (char *)"*vpeDeletePageOption.labelString:            Delete Page",
    (char *)"*vpeDeletePageOption.mnemonic:               D",
    (char *)"*vpeConfigurePageOption.labelString:         Configure Page...",
    (char *)"*vpeConfigurePageOption.mnemonic:            f",
    (char *)"*vpeJavaCascade.labelString:                 Java",
    (char *)"*vpeJavifyNetOption.labelString:             Add Tools",
    (char *)"*vpeUnjavifyNetOption.labelString:           Remove Tools",
    (char *)"*vpeSaveWebPageOption.labelString:           Save As Web Page",
    (char *)"*vpeSaveAppletOption.labelString:            Net to Applet",
    (char *)"*vpeSaveBeanOption.labelString:              Net to Bean",
    (char *)"*vpeReflowGraphOption.labelString:           Layout Graph",
    (char *)"*vpeReflowGraphOption.mnemonic:              u",
    (char *)"*vpeReflowGraphOption.accelerator:           Ctrl<Key>K",
    (char *)"*vpeReflowGraphOption.acceleratorText:       Ctrl+K",
    (char *)"*vpeStraightenArcsOption.labelString:        Tidy Up the Arcs",
    (char *)"*vpeStraightenArcsOption.mnemonic:           y",
    (char *)"*vpeMacroNameOption.labelString:             Macro Name...",
    (char *)"*vpeMacroNameOption.mnemonic:                N",
    (char *)"*vpeCreateProcessGroupOption.labelString:    Execution Groups...",
    (char *)"*vpeCreateProcessGroupOption.mnemonic:       G",
    (char *)"*vpeCommentOption.labelString:               Comment...",
    (char *)"*vpeCommentOption.mnemonic:                  o",
    (char *)"*windowsMenu.labelString:                    Windows",
    (char *)"*windowsMenu.mnemonic:                       W",
    (char *)"*vpeNewControlPanelOption.labelString:        New Control Panel",
    (char *)"*vpeNewControlPanelOption.mnemonic:           P",
    (char *)"*vpeOpenControlPanelOption.labelString:  Open Selected Control "
            "Panel(s)",
    (char *)"*vpeOpenControlPanelOption.mnemonic:          S",
    (char *)"*vpeOpenAllControlPanelsOption.labelString:   Open All Control "
            "Panels",
    (char *)"*vpeOpenAllControlPanelsOption.mnemonic:      A",
    (char *)"*vpeOpenAllControlPanelsOption.accelerator:   Ctrl<Key>P",
    (char *)"*vpeOpenAllControlPanelsOption.acceleratorText: Ctrl+P",
    (char *)"*vpePanelCascade.labelString:                 Open Control Panel "
            "by Name",
    (char *)"*vpePanelCascade.mnemonic:                    N",
    (char *)"*vpePanelGroupCascade.labelString:            Open Control Panel "
            "by Group",
    (char *)"*vpePanelGroupCascade.mnemonic:               G",
    (char *)"*vpeOpenMacroOption.labelString:              Open Selected "
            "Macro(s)",
    (char *)"*vpeOpenMacroOption.mnemonic:                 M",
    (char *)"*vpeOpenImageOption.labelString:             Open Selected Image "
            "Window(s)",
    (char *)"*vpeOpenImageOption.mnemonic:                 I",
    (char *)"*vpeOpenColormapEditorOption.labelString:Open Selected Colormap "
            "Editor(s)",
    (char *)"*vpeOpenColormapEditorOption.mnemonic:        C",
    (char *)"*vpeOpenColormapEditorOption.accelerator:     Ctrl<Key>E",
    (char *)"*vpeOpenColormapEditorOption.acceleratorText: Ctrl+E",
    (char *)"*vpeMessageWindowOption.labelString:          Open Message Window",
    (char *)"*vpeMessageWindowOption.mnemonic:             e",
    (char *)"*optionsMenu.labelString:                    Options",
    (char *)"*optionsMenu.mnemonic:                       O",
    (char *)"*vpeToolPalettesOption.labelString:          Tool Palettes",
    (char *)"*vpeToolPalettesOption.mnemonic:             T",
    (char *)"*vpeToolPalettesOption.accelerator:          Ctrl<Key>T",
    (char *)"*vpeToolPalettesOption.acceleratorText:      Ctrl+T",
    (char *)"*vpeHitDetectionOption.labelString:          Prevent Overlap",
    (char *)"*vpeHitDetectionOption.mnemonic:             v",
    (char *)"*vpeHitDetectionOption.accelerator:          Ctrl<Key>V",
    (char *)"*vpeHitDetectionOption.acceleratorText:      Ctrl+V",
    (char *)"*vpePanelAccessOption.labelString:           Control Panel "
            "Access...",
    (char *)"*vpePanelAccessOption.mnemonic:              A",
    (char *)"*vpePanelGroupOption.labelString:            Control Panel "
            "Groups...",
    (char *)"*vpePanelGroupOption.mnemonic:               P",
    (char *)"*vpeShowExecutedOption.labelString:	  Select Executed",
    (char *)"*vpeShowExecutedOption.mnemonic:		  S",
    (char *)"*vpeGridOption.labelString:                  Grid...",
    (char *)"*vpeGridOption.mnemonic:                     G",
    (char *)"*fileMenuPulldown.tearOffModel:		  XmTEAR_OFF_DISABLED",
    (char *)"*editMenuPulldown.tearOffModel:		  XmTEAR_OFF_DISABLED",
    (char *)"*windowsMenuPulldown.tearOffModel:		  XmTEAR_OFF_DISABLED",
    (char *)"*vpeOnVisualProgramOption.labelString:       Application "
            "Comment...",
    (char *)"*vpeOnVisualProgramOption.mnemonic:          A",
#if ( XmVersion > 1001 )
    (char *)"*workAreaFrame*traversalOn:                  false",
    (char *)"*workAreaFrame*XmWorkspace*traversalOn:      true",
#endif
    (char *)".mainWindow.commandWindowLocation: XmCOMMAND_ABOVE_WORKSPACE",
    (char *)".mainWindow.packing: 		XmPACK_NONE", NULL};

#else /* defined(DX_NEW_KEYLAYOUT) */

String EditorWindow::DefaultResources[] = {
    (char *)".title:                                      	Visual Program "
            "Editor",
    (char *)".iconName:                                   	VPE",
    (char *)".minWidth:                                   	480",
    (char *)".minHeight:                                  	400",
    (char *)"*workArea.width:                             	850",
    (char *)"*workArea.height:                            	650",
    (char *)"*notebook.width:				  	180",
    (char *)"*scrolledWindow*XmScrollBar.initialDelay:    	2000",
    (char *)"*scrolledWindow*XmScrollBar.repeatDelay:     	2000",
    (char *)"*fileMenu.labelString:                       	File",
    (char *)"*fileMenu.mnemonic:                          	F",
    (char *)"*vpeNewOption.labelString:                   	New",
    (char *)"*vpeNewOption.mnemonic:                      	N",
    (char *)"*vpeNewOption.accelerator:				Ctrl <Key>N",
    (char *)"*vpeNewOption.acceleratorText:			Ctrl+N",
    (char *)"*vpeOpenOption.labelString:                  	Open "
            "Program...",
    (char *)"*vpeOpenOption.mnemonic:                     	O",
    (char *)"*vpeOpenOption.accelerator:			Ctrl <Key>O",
    (char *)"*vpeOpenOption.acceleratorText:			Ctrl+O",
    (char *)"*vpeSaveOption.labelString:                  	Save Program",
    (char *)"*vpeSaveOption.mnemonic:                     	S",
    (char *)"*vpeSaveOption.accelerator:                  	Ctrl<Key>S",
    (char *)"*vpeSaveOption.acceleratorText:              	Ctrl+S",
    (char *)"*vpeSaveMacroOption.labelString:			Save Macro",
    (char *)"*vpeSaveMacroOption.mnemonic:			S",
    (char *)"*vpeSaveMacroOption.accelerator:			Ctrl<Key>S",
    (char *)"*vpeSaveMacroOption.acceleratorText:		Ctrl+S",
    (char *)"*vpeSaveAsOption.labelString:                	Save Program "
            "As...",
    (char *)"*vpeSaveAsOption.mnemonic:				A",
    (char *)"*vpeSaveAsOption.accelerator:			Ctrl Shift "
            "<Key>S",
    (char *)"*vpeSaveAsOption.acceleratorText:			Ctrl+Shift+S",
    (char *)"*vpeSaveMacroAsOption.labelString:                	Save "
            "Macro As...",
    (char *)"*vpeSaveMacroAsOption.mnemonic:			A",
    (char *)"*vpeSaveMacroAsOption.accelerator:			Ctrl "
            "Shift <Key>S",
    (char *)"*vpeSaveMacroAsOption.acceleratorText:		Ctrl+Shift+S",
    (char *)"*vpeSettingsCascade.labelString: 		  	Program "
            "Settings",
    (char *)"*vpeSettingsCascade.mnemonic: 		  	r",
    (char *)"*vpeSaveCfgOption.labelString:               	Save As...",
    (char *)"*vpeSaveCfgOption.mnemonic:                  	S",
    (char *)"*vpeOpenCfgOption.labelString:               	Load...",
    (char *)"*vpeOpenCfgOption.mnemonic:                  	L",
    (char *)"*vpePrintProgramOption.labelString:          	Print "
            "Program...",
    (char *)"*vpePrintProgramOption.mnemonic:             	P",
    (char *)"*vpePrintProgramOption.accelerator:		Ctrl <Key>P",
    (char *)"*vpePrintProgramOption.acceleratorText:		Ctrl+P",
    (char *)"*vpeLoadMDFOption.labelString:              	Load Module "
            "Description(s)...",
    (char *)"*vpeLoadMDFOption.mnemonic:                  	M",
    (char *)"*vpeLoadMacroOption.labelString:             	Load Macro...",
    (char *)"*vpeLoadMacroOption.mnemonic:                	L",
#ifdef DXUI_DEVKIT
    (char *)"*vpeSaveAsCCodeOption.labelString:           Save As C Code...",
    (char *)"*vpeSaveAsCCodeOption.mnemonic:              v",
#endif  // DXUI_DEVKIT
    (char *)"*vpeCloseOption.labelString:                 	Close",
    (char *)"*vpeCloseOption.mnemonic:                    	C",
    (char *)"*vpeCloseOption.accelerator:                 	Ctrl <Key>W",
    (char *)"*vpeCloseOption.acceleratorText:             	Ctrl+W",
    (char *)"*editMenu.labelString:                       	Edit",
    (char *)"*editMenu.mnemonic:                          	E",
    (char *)"*vpeUndoOption.labelString:                  	Undo",
    (char *)"*vpeUndoOption.accelerator:                  	Ctrl<Key>Z",
    (char *)"*vpeUndoOption.acceleratorText:              	Ctrl+Z",
    (char *)"*vpeValuesOption.labelString:                	"
            "Configuration...",
    (char *)"*vpeValuesOption.mnemonic:                   	R",
    (char *)"*vpeValuesOption.accelerator:                	Ctrl <Key>F",
    (char *)"*vpeValuesOption.acceleratorText:            	Ctrl+F",
    (char *)"*vpeFindToolOption.labelString:              	Find Tool...",
    (char *)"*vpeFindToolOption.mnemonic:                 	F",
    (char *)"*vpeEditTabsCascade.labelString: 		  	Input/Output "
            "Tabs",
    (char *)"*vpeEditTabsCascade.mnemonic: 		  	B",
    (char *)"*vpeAddInputTabOption.labelString:              	Add Input Tab",
    (char *)"*vpeAddInputTabOption.mnemonic:                 	A",
    (char *)"*vpeAddInputTabOption.accelerator:              	Ctrl <Key>A",
    (char *)"*vpeAddInputTabOption.acceleratorText:          	Ctrl+A",
    (char *)"*vpeRemoveInputTabOption.labelString:           	Remove Input "
            "Tab",
    (char *)"*vpeRemoveInputTabOption.mnemonic:              	R",
    (char *)"*vpeRemoveInputTabOption.accelerator:           	Ctrl <Key>R",
    (char *)"*vpeRemoveInputTabOption.acceleratorText:       	Ctrl+R",
    (char *)"*vpeAddOutputTabOption.labelString:             	Add Output Tab",
    (char *)"*vpeAddOutputTabOption.mnemonic:                	O",
    (char *)"*vpeRemoveOutputTabOption.labelString:          	Remove Output "
            "Tab",
    (char *)"*vpeRemoveOutputTabOption.mnemonic:             	T",
    (char *)"*vpeHideAllTabsOption.labelString:              	Hide All Tabs",
    (char *)"*vpeHideAllTabsOption.mnemonic:                 	H",
    (char *)"*vpeHideAllTabsOption.accelerator:              	Ctrl <Key>H",
    (char *)"*vpeHideAllTabsOption.acceleratorText:          	Ctrl+H",
    (char *)"*vpeRevealAllTabsOption.labelString:            	Reveal All "
            "Tabs",
    (char *)"*vpeRevealAllTabsOption.mnemonic:               	L",
    (char *)"*vpeRevealAllTabsOption.accelerator:            	Ctrl <Key>L",
    (char *)"*vpeRevealAllTabsOption.acceleratorText:        	Ctrl+L",
    (char *)"*vpeEditSelectCascade.labelString:		  	"
            "Select/Deselect Tools",
    (char *)"*vpeEditSelectCascade.mnemonic:		  	S",

#ifndef FORGET_GETSET
    (char *)"*programVerifyCascade.labelString:		  Assign Get/Set Scope",
    (char *)"*programVerifyCascade.mnemonic:		  V",
    (char *)"*getSetConversion.labelString:		  Convert All "
            "Modules...",
    (char *)"*getSetConversion.mnemonic:		  C",
    (char *)"*setToGlobal.labelString:		     	  Set Selected "
            "Gets/Sets Global",
    "*setToGlobal.mnemonic:		     	  G",
    "*setToLocal.labelString:		          Set Selected Gets/Sets Local",
    "*setToLocal.mnemonic:		       	  L",
#endif
    "*vpeSelectAllOption.labelString:                	Select All",
    "*vpeSelectAllOption.mnemonic:                   	S",
    "*vpeSelectAllOption.accelerator:			Ctrl Shift <Key>A",
    "*vpeSelectAllOption.acceleratorText:		Ctrl+Shift+A",
    "*vpeSelectConnectedOption.labelString:          	Select Connected",
    "*vpeSelectConnectedOption.mnemonic:             	C",
    "*vpeSelectUnconnectedOption.labelString:        	Select Unconnected",
    "*vpeSelectUnconnectedOption.mnemonic:           	U",
    "*vpeSelectUpwardOption.labelString:             	Select Upward",
    "*vpeSelectUpwardOption.mnemonic:                	P",
    "*vpeSelectDownwardOption.labelString:           	Select Downward",
    "*vpeSelectDownwardOption.mnemonic:              	D",
    "*vpeDeselectAllOption.labelString:              	Deselect All",
    "*vpeDeselectAllOption.mnemonic:                 	E",
    "*vpeDeselectAllOption.accelerator:			Ctrl Shift <Key>D",
    "*vpeDeselectAllOption.acceleratorText:		Ctrl+Shift+D",
    "*vpeSelectUnselectedOption.labelString:         	Select Unselected",
    "*vpeSelectUnselectedOption.mnemonic:            	N",
    "*vpeShowExecutedOption.labelString:	  	Select Executed",
    "*vpeShowExecutedOption.mnemonic:		  	X",
    "*vpeOutputCacheabilityCascade.labelString:      	Output Cacheability",
    "*vpeOutputCacheabilityCascade.mnemonic:         	y",
    "*vpeOptimizeCacheability.labelString:           	Optimize Cacheability",
    "*vpeOptimizeCacheability.mnemonic:              	O",
    "*vpeEditOutputCacheabilityCascade.labelString:  	Set Output "
    "Cacheability",
    "*vpeEditOutputCacheabilityCascade.mnemonic:     	S",
    "*vpeCacheAllOutputsOption.labelString:          	Cache All Results",
    "*vpeCacheAllOutputsOption.mnemonic:             	A",
    "*vpeCacheLastOutputsOption.labelString:         	Cache Last Result",
    "*vpeCacheLastOutputsOption.mnemonic:            	L",
    "*vpeCacheNoOutputsOption.labelString:           	Cache No Results",
    "*vpeCacheNoOutputsOption.mnemonic:              	N",
    "*vpeShowOutputCacheabilityCascade.labelString:  	Show Output "
    "Cacheability",
    "*vpeShowOutputCacheabilityCascade.mnemonic:     	h",
    "*vpeShowCacheAllOutputsOption.labelString:      	All Results",
    "*vpeShowCacheAllOutputsOption.mnemonic:         	A",
    "*vpeShowCacheLastOutputsOption.labelString:     	Last Result",
    "*vpeShowCacheLastOutputsOption.mnemonic:        	L",
    "*vpeShowCacheNoOutputsOption.labelString:       	No Results",
    "*vpeShowCacheNoOutputsOption.mnemonic:          	N",
    "*vpeCutOption.labelString:                      	Cut",
    "*vpeCutOption.mnemonic:                         	T",
    "*vpeCutOption.acceleratorText:                  	Ctrl+X",
    "*vpeCutOption.accelerator:                      	Ctrl <Key>X",
    "*vpeCopyOption.labelString:                     	Copy",
    "*vpeCopyOption.mnemonic:                        	C",
    "*vpeCopyOption.acceleratorText:                 	Ctrl+C",
    "*vpeCopyOption.accelerator:                     	Ctrl <Key>C",
    "*vpePasteOption.labelString:                    	Paste",
    "*vpePasteOption.mnemonic:                       	P",
    "*vpePasteOption.acceleratorText:                	Ctrl+V",
    "*vpePasteOption.accelerator:                    	Ctrl <Key>V",
    "*vpeDeleteOption.labelString:                   	Delete",
    "*vpeDeleteOption.mnemonic:                      	D",
#if defined( intelnt )
    "*vpeDeleteOption.acceleratorText:			Ctrl+Backspace",
#else
    "*vpeDeleteOption.acceleratorText:               	Ctrl+Delete",
#endif
#if defined( macos ) || defined( intelnt )
    "*vpeDeleteOption.accelerator:                   	Ctrl<Key>BackSpace",
#elif defined( aviion )
    "*vpeDeleteOption.accelerator:			Ctrl<Key>Delete",
#else
    "*vpeDeleteOption.accelerator:                   	Ctrl<Key>osfDelete",
#endif
    "*vpeAddDecorator.labelString:                	Add Annotation",
    "*vpeAddDecorator.mnemonic:                   	A",
    "*vpeInsertNetOption.labelString:             	Insert Visual "
    "Program...",
    "*vpeInsertNetOption.mnemonic:                	I",
    "*vpeCreateMacroOption.labelString:           	Create Macro...",
    "*vpeCreateMacroOption.mnemonic:              	M",
    "*vpePageCascade.labelString:                 	Page",
    "*vpePageCascade.mnemonic:				P",
    "*vpeCreatePageOption.labelString:            	Create Empty Page",
    "*vpeCreatePageOption.mnemonic:               	E",
    "*vpeSelectedPageOption.labelString:          	Create with Selected "
    "Tools",
    "*vpeSelectedPageOption.mnemonic:             	C",
    "*vpeMoveToPageOption.labelString:            	Move Selected Tools...",
    "*vpeMoveToPageOption.mnemonic:               	M",
    "*vpeChopPageOption.labelString:          	  	Separate Selected "
    "Tools",
    "*vpeChopPageOption.mnemonic:          	  	S",
    "*vpeFusePageOption.labelString:          	  	Reconnect Selected "
    "Tools",
    "*vpeFusePageOption.mnemonic:          	  	R",
    "*vpeDeletePageOption.labelString:            	Delete Page",
    "*vpeDeletePageOption.mnemonic:               	D",
    "*vpeConfigurePageOption.labelString:         	Configure Page...",
    "*vpeConfigurePageOption.mnemonic:            	F",
    "*vpeJavaCascade.labelString:                 	Java",
    "*vpeJavaCascade.mnemonic:				J",
    "*vpeJavifyNetOption.labelString:             	Add Tools",
    "*vpeUnjavifyNetOption.labelString:           	Remove Tools",
    "*vpeSaveWebPageOption.labelString:           	Save As Web Page",
    "*vpeSaveAppletOption.labelString:            	Net to Applet",
    "*vpeSaveBeanOption.labelString:              	Net to Bean",
    "*vpeReflowGraphOption.labelString:           	Layout Graph",
    "*vpeReflowGraphOption.mnemonic:              	u",
    "*vpeReflowGraphOption.accelerator:           	Ctrl<Key>K",
    "*vpeReflowGraphOption.acceleratorText:       	Ctrl+K",
    "*vpeStraightenArcsOption.labelString:        	Tidy Up the Arcs",
    "*vpeStraightenArcsOption.mnemonic:          	 y",
    "*vpeMacroNameOption.labelString:             	Macro Name...",
    "*vpeMacroNameOption.mnemonic:                	N",
    "*vpeCreateProcessGroupOption.labelString:    	Execution Groups...",
    "*vpeCreateProcessGroupOption.mnemonic:       	G",
    "*vpeCommentOption.labelString:               	Comment...",
    "*vpeCommentOption.mnemonic:                  	O",
    "*windowsMenu.labelString:                    	Windows",
    "*windowsMenu.mnemonic:                       	W",
    "*vpeNewControlPanelOption.labelString:        	New Control Panel",
    "*vpeNewControlPanelOption.mnemonic:           	P",
    "*vpeOpenControlPanelOption.labelString:  		Open Selected Control "
    "Panel(s)",
    "*vpeOpenControlPanelOption.mnemonic:          	S",
    "*vpeOpenAllControlPanelsOption.labelString:   	Open All Control "
    "Panels",
    "*vpeOpenAllControlPanelsOption.mnemonic:      	A",
    "*vpeOpenAllControlPanelsOption.accelerator:   	Ctrl Shift <Key>P",
    "*vpeOpenAllControlPanelsOption.acceleratorText: 	Ctrl+Shift+P",
    "*vpePanelCascade.labelString:                 	Open Control Panel by "
    "Name",
    "*vpePanelCascade.mnemonic:                    	N",
    "*vpePanelGroupCascade.labelString:            	Open Control Panel by "
    "Group",
    "*vpePanelGroupCascade.mnemonic:               	G",
    "*vpeOpenMacroOption.labelString:              	Open Selected Macro(s)",
    "*vpeOpenMacroOption.mnemonic:                 	R",
    "*vpeOpenImageOption.labelString:             	Open Selected Image "
    "Window(s)",
    "*vpeOpenImageOption.mnemonic:                 	I",
    "*vpeOpenColormapEditorOption.labelString:		Open Selected Colormap "
    "Editor(s)",
    "*vpeOpenColormapEditorOption.mnemonic:        	C",
    "*vpeOpenColormapEditorOption.accelerator:     	Ctrl Shift <Key>E",
    "*vpeOpenColormapEditorOption.acceleratorText: 	Ctrl+Shift+E",
    "*vpeMessageWindowOption.labelString:          	Open Message Window",
    "*vpeMessageWindowOption.mnemonic:             	M",
    "*vpeMessageWindowOption.accelerator:		Ctrl <Key>M",
    "*vpeMessageWindowOption.acceleratorText:		Ctrl+M",
    "*optionsMenu.labelString:                    	Options",
    "*optionsMenu.mnemonic:                       	O",
    "*vpeToolPalettesOption.labelString:          	Tool Palettes",
    "*vpeToolPalettesOption.mnemonic:             	T",
    "*vpeToolPalettesOption.accelerator:          	Ctrl<Key>T",
    "*vpeToolPalettesOption.acceleratorText:      	Ctrl+T",
    "*vpeHitDetectionOption.labelString:          	Prevent Overlap",
    "*vpeHitDetectionOption.mnemonic:             	v",
    "*vpePanelAccessOption.labelString:           	Control Panel "
    "Access...",
    "*vpePanelAccessOption.mnemonic:              	A",
    "*vpePanelGroupOption.labelString:            	Control Panel "
    "Groups...",
    "*vpePanelGroupOption.mnemonic:               	P",
    "*vpeGridOption.labelString:                  	Grid...",
    "*vpeGridOption.mnemonic:                     	G",
    "*fileMenuPulldown.tearOffModel:		  	XmTEAR_OFF_DISABLED",
    "*editMenuPulldown.tearOffModel:		  	XmTEAR_OFF_DISABLED",
    "*windowsMenuPulldown.tearOffModel:		  	XmTEAR_OFF_DISABLED",
    "*vpeOnVisualProgramOption.labelString:       	Application Comment...",
    "*vpeOnVisualProgramOption.mnemonic:          	A",
#if ( XmVersion > 1001 )
    "*workAreaFrame*traversalOn:                  false",
    "*workAreaFrame*XmWorkspace*traversalOn:      true",
#endif
    ".mainWindow.commandWindowLocation:	XmCOMMAND_ABOVE_WORKSPACE",
    ".mainWindow.packing: 		XmPACK_NONE", NULL};

#endif

#endif  // _EWDefaultResources_h
