

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;

int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + (yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[(yy_more_offset)], (yytext_ptr), yyleng + 1 ); \
	yyleng += (yy_more_offset); \
	(yy_prev_more_offset) = (yy_more_offset); \
	(yy_more_offset) = 0; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 122
#define YY_END_OF_BUFFER 123
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[557] =
    {   0,
      123,  122,  121,  122,   21,  122,  122,  119,  122,  120,
      122,   41,  122,  122,   49,  122,   50,  122,   39,  122,
       37,  122,   58,  122,   38,  122,  122,   40,  122,  113,
      122,  113,  122,   59,  122,   60,  122,   34,  122,   55,
      122,   35,  122,  108,  122,  107,  110,  122,  107,  110,
      122,  107,  110,  122,  107,  110,  122,  107,  110,  122,
      107,  110,  122,  107,  110,  122,  107,  110,  122,   53,
      122,   54,  122,   46,  122,  107,  110,  122,  107,  110,
      122,  107,  110,  122,  107,  110,  122,  107,  110,  122,
      107,  110,  122,  107,  110,  122,  107,  110,  122,  107,

      110,  122,  107,  110,  122,  107,  110,  122,  107,  110,
      122,  107,  110,  122,  107,  110,  122,  107,  110,  122,
      107,  110,  122,  107,  110,  122,  107,  110,  122,   51,
      122,   48,  122,   52,  122,  121,   31,  117,  119,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
       13,   47,   61,  113,   62,   63,   64,  115,  118,  114,
      112,  113,   56,   57,   32,   36,   30,   33,  109,  107,
      110,  110,  107,  110,  107,  110,  107,  110,  107,  110,
      107,  110,  107,  110,  107,  110,    6,  107,  110,   17,
      107,  110,  107,  110,  107,  110,  107,  110,  107,  110,

      107,  110,  107,  110,  107,  110,  107,  110,   70,  107,
      110,  107,  110,  107,  110,  107,  110,  107,  110,  107,
      110,  107,  110,    5,   77,  107,  110,   18,  107,  110,
      107,  110,  107,  110,  107,  110,  107,  110,  107,  110,
      107,  110,  107,  110,  107,  110,  107,  110,  107,  110,
      107,  110,   14,  117,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  118,
      114,  115,  116,  111,   15,  107,  110,   45,  107,  110,
      107,  110,   43,  107,  110,   22,  107,  110,  107,  110,
        8,  107,  110,  107,  110,   16,  107,  110,  107,  110,

      107,  110,   44,  107,  110,  107,  110,  107,  110,   68,
      107,  110,  107,  110,  107,  110,  107,  110,   42,  107,
      110,   23,  107,  110,    7,   76,  107,  110,  107,  110,
      107,  110,  107,  110,  107,  110,  107,  110,  107,  110,
      107,  110,  107,  110,  107,  110,  107,  110,  107,  110,
      107,  110,  107,  110,  107,  110,   91,  120,   92,  120,
       93,  120,   94,  120,   95,  120,   96,  120,   97,  120,
       98,  120,   99,  120,  100,  120,  101,  120,  102,  120,
      103,  120,  104,  120,  105,  120,  106,  120,  115,   24,
       27,   29,   26,   28,   25,   11,   12,  114,  107,  110,

       75,  107,  110,    2,  107,  110,  107,  110,  107,  110,
       67,  107,  110,  107,  110,  107,  110,  107,  110,   72,
      107,  110,  107,  110,  107,  110,  107,  110,  107,  110,
       80,  107,  110,   81,  107,  110,  107,  110,  107,  110,
      107,  110,   85,  107,  110,   86,  107,  110,  107,  110,
       88,  107,  110,    1,  107,  110,  107,  110,  107,  110,
        9,   19,   10,   20,  114,  115,    4,  107,  110,  107,
      110,  107,  110,    3,  107,  110,  107,  110,  107,  110,
       73,  107,  110,  107,  110,  107,  110,   79,  107,  110,
      107,  110,  107,  110,  107,  110,  107,  110,   89,  107,

      110,   90,  107,  110,  107,  110,   66,  107,  110,  107,
      110,  107,  110,   74,  107,  110,  107,  110,   82,  107,
      110,   83,  107,  110,  107,  110,  107,  110,  107,  110,
       69,  107,  110,   71,  107,  110,  107,  110,  107,  110,
       87,  107,  110,   65,  107,  110,  107,  110,   84,  107,
      110,  107,  110,   78,  107,  110
    } ;

static yyconst flex_int16_t yy_accept[321] =
    {   0,
        1,    1,    1,    2,    3,    5,    7,    8,   10,   12,
       14,   15,   17,   19,   21,   23,   25,   27,   28,   30,
       32,   34,   36,   38,   40,   42,   44,   46,   49,   52,
       55,   58,   61,   64,   67,   70,   72,   74,   76,   79,
       82,   85,   88,   91,   94,   97,  100,  103,  106,  109,
      112,  115,  118,  121,  124,  127,  130,  132,  134,  136,
      137,  138,  138,  139,  139,  140,  141,  142,  143,  144,
      145,  146,  147,  148,  149,  150,  151,  152,  153,  154,
      154,  155,  156,  157,  158,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  160,  161,  163,  163,  163,

      164,  165,  166,  167,  168,  169,  170,  172,  173,  175,
      177,  179,  181,  183,  185,  187,  190,  193,  195,  197,
      199,  201,  203,  205,  207,  209,  212,  214,  216,  218,
      220,  222,  224,  228,  231,  233,  235,  237,  239,  241,
      243,  245,  247,  249,  251,  253,  254,  255,  256,  257,
      258,  259,  260,  261,  262,  263,  264,  265,  266,  267,
      268,  269,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  271,  273,  273,  273,
      274,  275,  278,  281,  283,  286,  289,  291,  294,  296,
      299,  301,  303,  306,  308,  310,  313,  315,  317,  319,

      322,  325,  329,  331,  333,  335,  337,  339,  341,  343,
      345,  347,  349,  351,  353,  355,  357,  359,  361,  363,
      365,  367,  369,  371,  373,  375,  377,  379,  381,  383,
      385,  387,  389,  389,  390,  390,  391,  392,  393,  394,
      395,  396,  396,  397,  397,  397,  398,  398,  398,  399,
      401,  404,  407,  409,  411,  414,  416,  418,  420,  423,
      425,  427,  429,  431,  434,  437,  439,  441,  443,  446,
      449,  451,  454,  457,  459,  461,  462,  463,  464,  465,
      465,  467,  470,  472,  474,  477,  479,  481,  484,  486,
      488,  491,  493,  495,  497,  499,  502,  505,  507,  510,

      512,  514,  517,  519,  522,  525,  527,  529,  531,  534,
      537,  539,  541,  544,  547,  549,  552,  554,  557,  557
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   30,   31,   32,   33,
       34,   28,   35,   28,   28,   36,   37,   38,   39,   28,
       40,   41,   42,   43,   44,   45,   28,   46,   28,   28,
       47,   48,   49,   50,   28,    1,   51,   52,   53,   54,

       55,   56,   28,   57,   58,   28,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,   69,   70,   71,   46,
       72,   28,   73,   74,   75,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[76] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    1,    1,    1,    1,    1,    3,    3,    4,    4,
        4,    4,    4,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[328] =
    {   0,
        0,    0,  595,  596,   74,  569,   73,    0,   28,  596,
      584,  596,  596,  579,   73,  596,   80,  105,  573,   96,
       91,  565,  596,   93,  564,  563,    0,  560,   64,  100,
       76,   93,  106,  120,  111,  596,  596,  596,   87,   80,
      103,  102,  109,  113,  121,  128,  130,  132,  136,  139,
      135,  145,  146,  151,  143,  152,  596,  512,  596,  172,
      596,  175,  596,  177,    0,    0,  532,  533,  532,  516,
      518,  518,  128,   30,  131,  130,  596,  596,  596,  191,
      199,  596,  596,  596,  207,  541,  538,  181,  189,  190,
      536,  514,  512,  508,    0,  214,  221,  229,    0,  596,

      596,  596,  596,  596,  596,    0,  546,    0,  220,  210,
      225,  229,  144,  230,  203,  545,  544,  231,  217,  232,
      236,  237,  238,  240,  243,  543,  241,  245,  246,  247,
      138,  250,  542,  541,  251,  252,  254,  255,  253,  260,
      257,  259,  256,  261,  263,  596,  284,  508,  513,  497,
      498,  497,  236,  500,  506,  507,  492,  496,  502,  489,
      493,  499,  314,  522,  535,  534,  533,  532,  531,  530,
      503,  528,  490,  475,  525,    0,  317,  325,  276,  331,
        0,  514,  513,  275,  512,  511,  304,  510,  315,  509,
      289,  300,  508,  299,  316,  286,  328,  329,  331,  332,

      507,  506,  333,  335,  334,  336,  337,  338,  339,  341,
      346,  347,  350,  340,  342,  343,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  359,  365,  515,  596,  596,  596,  596,  596,
      596,  514,  596,  513,  512,  596,  399,  402,  405,  344,
      501,  496,  360,  354,  488,  362,  348,  363,  484,  367,
      369,  371,  387,  480,  477,  389,  400,  401,  475,  474,
      407,  472,  468,  408,  409,  596,  596,  596,  596,  418,
      424,  466,  414,  419,  458,  420,  421,  456,  422,  424,
      455,  423,  425,  426,  427,  454,  449,  428,  447,  430,

      432,  446,  431,  433,  355,  439,  436,  442,  283,  266,
      440,  443,  264,  180,  444,  158,  445,  157,  596,  505,
      509,  513,  515,  517,  521,  100,  523
    } ;

static yyconst flex_int16_t yy_def[328] =
    {   0,
      319,    1,  319,  319,  319,  319,  320,  321,  322,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  323,  324,  324,  324,
      324,  324,  324,  324,  324,  319,  319,  319,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  319,  319,  319,  319,
      319,  320,  319,  320,  321,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  325,  319,  319,  319,  326,  319,

      319,  319,  319,  319,  319,  323,  324,  327,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  319,  320,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  325,  319,  319,  319,  319,
      326,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  319,  319,  319,  319,  319,
      319,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,    0,  319,
      319,  319,  319,  319,  319,  319,  319
    } ;

static yyconst flex_int16_t yy_nxt[672] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,    4,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   28,
       30,   28,   31,   28,   28,   28,   32,   33,   34,   28,
       28,   28,   35,   28,   28,   28,   36,    4,   37,   38,
       39,   40,   41,   42,   43,   44,   28,   45,   28,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   28,
       56,   28,   57,   58,   59,   60,   60,   63,   67,   68,
      156,   69,   70,   71,  157,   72,   79,   73,   74,   80,
      108,   81,   81,   81,   75,   82,   80,   76,   81,   81,

       81,  109,  108,  181,  111,   83,  108,   96,  101,   81,
       81,   81,   96,  108,   97,   97,   81,  102,  103,  108,
       64,   84,   98,   85,   85,   85,  108,   98,  108,  108,
      120,  112,  108,   86,  110,  108,   87,  108,   88,  108,
       89,   99,   90,   91,  113,   98,  108,  108,  119,  114,
       98,  118,  115,  121,  108,   92,  108,  116,  108,  122,
      117,  108,  108,  124,  108,  108,   93,   94,  123,  108,
      108,  108,  108,   60,   60,  125,  126,  108,  108,   63,
      129,  147,  127,  108,  108,  154,  186,  161,  158,  135,
      128,  132,  130,  155,  131,  162,  159,  133,  136,  138,

      139,  134,  160,  137,  144,  201,  108,  142,  145,   85,
       85,   85,  166,  140,  141,   96,  143,   81,   81,   81,
      168,  170,   64,  167,   64,   85,   85,   85,  171,  108,
       98,  169,  177,  177,  177,  188,  108,   96,  163,   97,
       97,   81,  179,  108,  179,  178,  108,  180,  180,  180,
      182,  108,   98,   98,  183,  108,  108,  108,  108,  185,
      184,  163,  108,  108,  108,  187,  108,  108,  178,  108,
      190,  108,  108,  108,  189,   98,  108,  108,  108,  108,
      108,  108,  108,  108,  191,  108,  108,  108,   63,  108,
      108,  222,  108,  197,  180,  180,  180,  192,  199,  195,

      200,  108,  205,  223,  194,  202,  193,  198,  196,  108,
      203,  206,  108,  213,  210,  108,  250,  209,  207,  204,
      216,  208,  211,  212,  214,  108,  108,  233,  215,  233,
      108,   64,  234,  234,  234,  177,  177,  177,  248,  251,
      248,  108,  108,  249,  249,  249,  252,  253,  247,  180,
      180,  180,  254,  255,  108,  108,  257,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  247,  108,  108,  108,  282,  108,  234,  234,  234,
      108,  108,  256,  234,  234,  234,  108,  258,  108,  108,
      262,  266,  259,  108,  273,  108,  260,  108,  286,  274,

      261,  263,  275,  265,  269,  264,  267,  268,  284,  270,
      271,  272,  280,  108,  280,  108,  285,  281,  281,  281,
      249,  249,  249,  249,  249,  249,  108,  108,  289,  288,
      283,  287,  290,  108,  108,  108,  281,  281,  281,  292,
      108,  291,  281,  281,  281,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  294,  108,  108,  108,  108,
      293,  295,  108,  297,  298,  108,  108,  296,  108,  108,
      108,  108,  108,  108,  301,  108,  302,  303,  299,  305,
      108,  108,  108,  309,  108,  300,  310,  306,  307,  313,
      304,  312,  108,  308,  108,  314,  311,  316,  108,  318,

      108,  108,  315,  108,  317,   62,  108,   62,   62,   65,
      108,   65,   65,   66,  108,   66,   66,  106,  106,  107,
      107,  176,  108,  176,  176,  108,  108,  108,  279,  278,
      277,  276,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  221,  220,  219,  218,  217,  108,  108,  108,
      108,  108,  108,  175,  174,  173,  172,  165,  164,  153,
      152,  151,  150,  149,  148,  146,  108,  105,  104,  100,
       95,   78,   77,   61,  319,    3,  319,  319,  319,  319,

      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319
    } ;

static yyconst flex_int16_t yy_chk[672] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    7,    9,    9,
       74,    9,    9,    9,   74,    9,   15,    9,    9,   15,
       29,   15,   15,   15,    9,   17,   17,    9,   17,   17,

       17,   29,   31,  326,   31,   17,   40,   21,   24,   21,
       21,   21,   20,   39,   20,   20,   20,   24,   24,   32,
        7,   18,   21,   18,   18,   18,   30,   20,   42,   41,
       40,   32,   33,   18,   30,   43,   18,   35,   18,   44,
       18,   20,   18,   18,   33,   21,   34,   45,   39,   33,
       20,   35,   34,   41,   46,   18,   47,   34,   48,   42,
       34,   51,   49,   44,  131,   50,   18,   18,   43,   55,
      113,   52,   53,   60,   60,   44,   45,   54,   56,   62,
       47,   64,   45,  318,  316,   73,  113,   76,   75,   50,
       46,   49,   47,   73,   48,   76,   75,   49,   50,   52,

       53,   49,   75,   51,   55,  131,  314,   54,   56,   80,
       80,   80,   88,   53,   53,   81,   54,   81,   81,   81,
       89,   90,   62,   88,   64,   85,   85,   85,   90,  115,
       81,   89,   96,   96,   96,  115,  110,   97,   85,   97,
       97,   97,   98,  119,   98,   96,  109,   98,   98,   98,
      109,  111,   97,   81,  110,  112,  114,  118,  120,  112,
      111,   85,  121,  122,  123,  114,  124,  127,   96,  125,
      119,  128,  129,  130,  118,   97,  132,  135,  136,  139,
      137,  138,  143,  141,  120,  142,  140,  144,  147,  145,
      313,  153,  310,  127,  179,  179,  179,  121,  129,  124,

      130,  184,  136,  153,  123,  132,  122,  128,  125,  309,
      135,  137,  196,  142,  140,  191,  184,  139,  138,  135,
      145,  138,  140,  141,  143,  194,  192,  163,  144,  163,
      187,  147,  163,  163,  163,  177,  177,  177,  178,  187,
      178,  189,  195,  178,  178,  178,  189,  191,  177,  180,
      180,  180,  192,  194,  197,  198,  196,  199,  200,  203,
      205,  204,  206,  207,  208,  209,  214,  210,  215,  216,
      250,  177,  211,  212,  257,  250,  213,  233,  233,  233,
      254,  305,  195,  234,  234,  234,  253,  197,  256,  258,
      203,  207,  198,  260,  214,  261,  199,  262,  257,  215,

      200,  204,  216,  206,  210,  205,  208,  209,  254,  211,
      212,  213,  247,  263,  247,  266,  256,  247,  247,  247,
      248,  248,  248,  249,  249,  249,  267,  268,  261,  260,
      253,  258,  262,  271,  274,  275,  280,  280,  280,  266,
      283,  263,  281,  281,  281,  284,  286,  287,  289,  292,
      290,  293,  294,  295,  298,  268,  300,  303,  301,  304,
      267,  271,  307,  275,  283,  306,  311,  274,  308,  312,
      315,  317,  302,  299,  287,  297,  289,  290,  284,  293,
      296,  291,  288,  300,  285,  286,  301,  294,  295,  307,
      292,  306,  282,  298,  273,  308,  303,  312,  272,  317,

      270,  269,  311,  265,  315,  320,  264,  320,  320,  321,
      259,  321,  321,  322,  255,  322,  322,  323,  323,  324,
      324,  325,  252,  325,  325,  327,  327,  251,  245,  244,
      242,  235,  202,  201,  193,  190,  188,  186,  185,  183,
      182,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  162,  161,  160,  159,  158,  157,  156,
      155,  154,  152,  151,  150,  149,  148,  134,  133,  126,
      117,  116,  107,   94,   93,   92,   91,   87,   86,   72,
       71,   70,   69,   68,   67,   58,   28,   26,   25,   22,
       19,   14,   11,    6,    3,  319,  319,  319,  319,  319,

      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[123] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() ((yy_more_offset) = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(yy_more_offset) = (yy_prev_more_offset); \
	yyleng -= (yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;

/***********************************************************************/
/* Open Visualization Data Explorer                                    */
/* (C) Copyright IBM Corp. 1989,1999                                   */
/* ALL RIGHTS RESERVED                                                 */
/* This code licensed under the                                        */
/*    "IBM PUBLIC LICENSE - Open Visualization Data Explorer"          */
/***********************************************************************/

/*****************************************************************************/
/* uin.lex -								     */
/*                                                                           */
/* Contains symbols for the SVS script language grammar.		     */
/*                                                                           */
/*****************************************************************************/

/*
 * $Header: /src/master/dx/src/uipp/dxuilib/net.lex,v 1.4 2002/02/06 19:17:29 davidt Exp $
 * $Log: net.lex,v $
 * Revision 1.4  2002/02/06 19:17:29  davidt
 * Have you ever wondered why after loading a network with a missing macro,
 * that you get all kinds of errors while trying to load the next program?
 * This is due to the fact that the lexer was not having its state machine
 * reset. This fix adds the code to do this so now you can open a program
 * with an error, then open a second program without getting a screen full
 * of errors. Tested with flex and Sun's lex.
 *
 * Revision 1.3  1999/05/10 15:46:23  gda
 * Copyright message
 *
 * Revision 1.3  1999/05/10 15:46:23  gda
 * Copyright message
 *
 * Revision 1.2  1999/04/01 20:06:03  gda
 * Added type for bison
 *
 * Revision 1.1.1.1  1999/03/24 15:18:18  gda
 * Initial CVS Version
 *
Revision 9.1  1997/05/22  19:46:49  svs
Copy of release 3.1.4 code

Revision 8.2  1996/01/24  21:48:38  dawood
mbsinvalid defined as null for NT also (for ajay).

Revision 8.1  1995/12/14  19:10:59  dawood
Added support for \r as a white space character, which helps us to
better support the NT and OS/2 ports which right out their .nets with
CR and LF instead of just LF.

Revision 8.0  1995/10/03  19:24:41  nsc
Copy of release 3.1 code

Revision 7.5  1995/03/24  22:33:50  dawood
Add NULL as a keyword (K_NULL) so that we can support static macros
which have input values inside the macro def.  Sometimes these values
are NULL.

Revision 7.4  1994/05/12  22:31:10  suits
Include string.h instead of single prototype of strcpy

Revision 7.3  1994/04/18  16:10:35  suits
OS2 definition of mbsinvalid

Revision 7.2  94/04/05  11:23:57  dawood
Change union to contain a string buffer, and change net.lex to do
strcpy() instead of strdup().  This fixes a memory leak such that
the strdup()'d string was not being freed.

Revision 7.1  94/01/18  19:20:01  svs
changes since release 2.0.1

Revision 6.1  93/11/16  11:09:17  svs
ship level code, release 2.0

Revision 1.3  93/10/07  15:52:07  cpv
Fixed the $command comment handling.

Revision 1.2  93/10/07  15:40:38  cpv
Accept "$.*" as an empty comment.

Revision 1.1  93/01/08  13:22:31  cpv
Initial revision

Revision 5.0  92/11/17  17:03:42  svs
ship level code, internal rev 1.2.2

Revision 4.0  92/08/18  15:54:50  svs
ship level code, rev 1.2

Revision 3.1  92/06/01  15:56:53  jgv
HP port.

Revision 3.0  91/11/27  17:02:50  svs
ship level code, rev 1.0

Revision 1.5  91/11/07  19:00:35  rbk
Added the latest exec's reserved keywords to the language.

Revision 1.4  91/11/06  17:52:28  rbk
Removed obsolete keywords.

Revision 1.3  91/08/20  16:39:11  rbk
Changed "UM" (unary minus) to "US" (unary sign), allowing unary "+"'s.

Revision 1.2  91/04/17  16:55:51  rbk
Added support for the new list constructor syntax.

Revision 1.1  91/03/19  15:55:27  rbk
Initial revision

Revision 1.4  91/03/18  16:26:35  rbk
Modified code to correctly parse long comment strings.

Revision 1.3  91/01/23  10:10:03  rbk
Removed K_FRAME token and added unary minus to numeric constants.

Revision 1.2  90/12/10  15:37:03  rbk
Added "@FRAME" and "@frame" to list of keywords to be lex'd.

Revision 1.1  90/10/11  18:32:48  rbk
Initial revision

 */

#include <math.h>

#if defined(OS2)  || defined(DXD_WIN)
#define mbsinvalid(x) 0
#endif 

#include <string.h>

#ifdef YYLMAX
#undef YYLMAX
#endif

#define YYLMAX 4096

int yylexerstate = 0;


#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    

	{ /* This code is run whenever yylex() is called */
	  if (yylexerstate == 1) {
	    BEGIN(INITIAL);
	#ifdef FLEX_SCANNER
	    yyrestart(yyin );
	#endif
	    yylexerstate = 0;
	  }
	}


	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 320 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 596 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_prev_more_offset); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
{ return (V_TRUE); }
	YY_BREAK
case 2:
YY_RULE_SETUP
{ return (V_TRUE); }
	YY_BREAK
case 3:
YY_RULE_SETUP
{ return (V_FALSE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
{ return (V_FALSE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
{ return (V_TRUE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
{ return (V_TRUE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
{ return (V_FALSE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
{ return (V_FALSE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
{ return (L_AND); }
	YY_BREAK
case 10:
YY_RULE_SETUP
{ return (L_AND); }
	YY_BREAK
case 11:
YY_RULE_SETUP
{ return (L_OR); }
	YY_BREAK
case 12:
YY_RULE_SETUP
{ return (L_OR); }
	YY_BREAK
case 13:
YY_RULE_SETUP
{ return (L_AND); }
	YY_BREAK
case 14:
YY_RULE_SETUP
{ return (L_OR); }
	YY_BREAK
case 15:
YY_RULE_SETUP
{ return (L_AND); }
	YY_BREAK
case 16:
YY_RULE_SETUP
{ return (L_AND); }
	YY_BREAK
case 17:
YY_RULE_SETUP
{ return (L_OR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
{ return (L_OR); }
	YY_BREAK
case 19:
YY_RULE_SETUP
{ return (L_NOT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
{ return (L_NOT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
{ return (L_NOT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
{ return (L_NOT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
{ return (L_NOT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
{ return (L_EQ); }
	YY_BREAK
case 25:
YY_RULE_SETUP
{ return (L_NEQ); }
	YY_BREAK
case 26:
YY_RULE_SETUP
{ return (L_LEQ); }
	YY_BREAK
case 27:
YY_RULE_SETUP
{ return (L_GEQ); }
	YY_BREAK
case 28:
YY_RULE_SETUP
{ return (L_LT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
{ return (L_GT); }
	YY_BREAK
case 30:
YY_RULE_SETUP
{ return (L_EQ); }
	YY_BREAK
case 31:
YY_RULE_SETUP
{ return (L_NEQ); }
	YY_BREAK
case 32:
YY_RULE_SETUP
{ return (L_LEQ); }
	YY_BREAK
case 33:
YY_RULE_SETUP
{ return (L_GEQ); }
	YY_BREAK
case 34:
YY_RULE_SETUP
{ return (L_LT); }
	YY_BREAK
case 35:
YY_RULE_SETUP
{ return (L_GT); }
	YY_BREAK
case 36:
YY_RULE_SETUP
{ return (L_NEQ); }
	YY_BREAK
case 37:
YY_RULE_SETUP
{ return (A_PLUS); }
	YY_BREAK
case 38:
YY_RULE_SETUP
{ return (A_MINUS); }
	YY_BREAK
case 39:
YY_RULE_SETUP
{ return (A_TIMES); }
	YY_BREAK
case 40:
YY_RULE_SETUP
{ return (A_DIV); }
	YY_BREAK
case 41:
YY_RULE_SETUP
{ return (A_MOD); }
	YY_BREAK
case 42:
YY_RULE_SETUP
{ return (A_MOD); }
	YY_BREAK
case 43:
YY_RULE_SETUP
{ return (A_MOD); }
	YY_BREAK
case 44:
YY_RULE_SETUP
{ return (A_IDIV); }
	YY_BREAK
case 45:
YY_RULE_SETUP
{ return (A_IDIV); }
	YY_BREAK
case 46:
YY_RULE_SETUP
{ return (A_EXP); }
	YY_BREAK
case 47:
YY_RULE_SETUP
{ return (A_EXP); }
	YY_BREAK
case 48:
YY_RULE_SETUP
{ return (T_BAR); }
	YY_BREAK
case 49:
YY_RULE_SETUP
{ return (T_LPAR); }
	YY_BREAK
case 50:
YY_RULE_SETUP
{ return (T_RPAR); }
	YY_BREAK
case 51:
YY_RULE_SETUP
{ return (T_LBRA); }
	YY_BREAK
case 52:
YY_RULE_SETUP
{ return (T_RBRA); }
	YY_BREAK
case 53:
YY_RULE_SETUP
{ return (T_LSQB); }
	YY_BREAK
case 54:
YY_RULE_SETUP
{ return (T_RSQB); }
	YY_BREAK
case 55:
YY_RULE_SETUP
{ return (T_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
{ return (T_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
{ return (T_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
{ return (T_COMMA); }
	YY_BREAK
case 59:
YY_RULE_SETUP
{ return (T_COLON); }
	YY_BREAK
case 60:
YY_RULE_SETUP
{ return (T_SEMI); }
	YY_BREAK
case 61:
YY_RULE_SETUP
{ return (T_PP); }
	YY_BREAK
case 62:
YY_RULE_SETUP
{ return (T_MM); }
	YY_BREAK
case 63:
YY_RULE_SETUP
{ return (T_RA); }
	YY_BREAK
case 64:
YY_RULE_SETUP
{ return (T_DOTDOT); }
	YY_BREAK
case 65:
YY_RULE_SETUP
{ return (K_BACKWARD); }
	YY_BREAK
case 66:
YY_RULE_SETUP
{ return (K_CANCEL); }
	YY_BREAK
case 67:
YY_RULE_SETUP
{ return (K_ELSE); }
	YY_BREAK
case 68:
YY_RULE_SETUP
{ return (K_FOR); }
	YY_BREAK
case 69:
YY_RULE_SETUP
{ return (K_FORWARD); }
	YY_BREAK
case 70:
YY_RULE_SETUP
{ return (K_IF); }
	YY_BREAK
case 71:
YY_RULE_SETUP
{ return (K_INCLUDE); }
	YY_BREAK
case 72:
YY_RULE_SETUP
{ return (K_LOOP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
{ return (K_MACRO); }
	YY_BREAK
case 74:
YY_RULE_SETUP
{ return (K_MODULE); }
	YY_BREAK
case 75:
YY_RULE_SETUP
{ return (K_NULL); }
	YY_BREAK
case 76:
YY_RULE_SETUP
{ return (K_OFF); }
	YY_BREAK
case 77:
YY_RULE_SETUP
{ return (K_ON); }
	YY_BREAK
case 78:
YY_RULE_SETUP
{ return (K_PALINDROME); }
	YY_BREAK
case 79:
YY_RULE_SETUP
{ return (K_PAUSE); }
	YY_BREAK
case 80:
YY_RULE_SETUP
{ return (K_PLAY); }
	YY_BREAK
case 81:
YY_RULE_SETUP
{ return (K_QUIT); }
	YY_BREAK
case 82:
YY_RULE_SETUP
{ return (K_REPEAT); }
	YY_BREAK
case 83:
YY_RULE_SETUP
{ return (K_RESUME); }
	YY_BREAK
case 84:
YY_RULE_SETUP
{ return (K_SEQUENCE); }
	YY_BREAK
case 85:
YY_RULE_SETUP
{ return (K_STEP); }
	YY_BREAK
case 86:
YY_RULE_SETUP
{ return (K_STOP); }
	YY_BREAK
case 87:
YY_RULE_SETUP
{ return (K_SUSPEND); }
	YY_BREAK
case 88:
YY_RULE_SETUP
{ return (K_THEN); }
	YY_BREAK
case 89:
YY_RULE_SETUP
{ return (K_UNTIL); }
	YY_BREAK
case 90:
YY_RULE_SETUP
{ return (K_WHILE); }
	YY_BREAK
case 91:
YY_RULE_SETUP
{ return (P_ACK); }
	YY_BREAK
case 92:
YY_RULE_SETUP
{ return (P_BACKGROUND); }
	YY_BREAK
case 93:
YY_RULE_SETUP
{ return (P_DATA); }
	YY_BREAK
case 94:
YY_RULE_SETUP
{ return (P_ERROR); }
	YY_BREAK
case 95:
YY_RULE_SETUP
{ return (P_FOREGROUND); }
	YY_BREAK
case 96:
YY_RULE_SETUP
{ return (P_INFO); }
	YY_BREAK
case 97:
YY_RULE_SETUP
{ return (P_INTERRUPT); }
	YY_BREAK
case 98:
YY_RULE_SETUP
{ return (P_LINQ); }
	YY_BREAK
case 99:
YY_RULE_SETUP
{ return (P_LRESP); }
	YY_BREAK
case 100:
YY_RULE_SETUP
{ return (P_MACRO); }
	YY_BREAK
case 101:
YY_RULE_SETUP
{ return (P_MESSAGE); }
	YY_BREAK
case 102:
YY_RULE_SETUP
{ return (P_SINQ); }
	YY_BREAK
case 103:
YY_RULE_SETUP
{ return (P_SRESP); }
	YY_BREAK
case 104:
YY_RULE_SETUP
{ return (P_SYSTEM); }
	YY_BREAK
case 105:
YY_RULE_SETUP
{ return (P_VINQ); }
	YY_BREAK
case 106:
YY_RULE_SETUP
{ return (P_VRESP); }
	YY_BREAK
case 107:
YY_RULE_SETUP
{
	                    strcpy (yylval.ast.s, yytext);
	                    return (T_ID);
	                }
	YY_BREAK
case 108:
case 109:
case 110:
YY_RULE_SETUP
{
	                    /* $$$$$ Reduce the expression */
	                    strcpy (yylval.ast.s, yytext);
	                    return (T_EXID);
	                }
	YY_BREAK
case 111:
case 112:
case 113:
YY_RULE_SETUP
{
	                    yylval.ast.i = strtol (yytext, NULL, 0);
	                    return (T_INT);
	                }
	YY_BREAK
case 114:
case 115:
case 116:
YY_RULE_SETUP
{
	                    yylval.ast.f = (float) atof (yytext);
	                    return (T_FLOAT);
	                }
	YY_BREAK
case 117:
YY_RULE_SETUP
{
	                    /* Strips off enclosing quotes */
	                    /* $$$$$ still need to process the string */
	                    yytext[strlen (yytext) - 1] = '\000';
	                    strcpy (yylval.ast.s, yytext+1);
	                    return (T_STRING);
	                }
	YY_BREAK
case 118:
YY_RULE_SETUP
{
	                    strcpy (yylval.ast.s, yytext+2);
	                    return (T_COMMENT);
	                }
	YY_BREAK
case 119:
YY_RULE_SETUP
{
	                    strcpy (yylval.ast.s, yytext+1);
	                    return (T_COMMENT);
	                }
	YY_BREAK
case 120:
YY_RULE_SETUP
{
	                    strcpy (yylval.ast.s, "");
	                    return (T_COMMENT);
	                }
	YY_BREAK
case 121:
/* rule 121 can match eol */
YY_RULE_SETUP
{ }
	YY_BREAK
case 122:
YY_RULE_SETUP
ECHO;
	YY_BREAK
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 320 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 320 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 319);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"



int
yywrap()
{
    return (1);
}

