"macro VRMLExport(",
" object",
",base_name",
") -> (",
" file_written",
") {",
"VRMLExport_Inp7_o1 = object;",
"VRMLExport_Inp8_o1 = base_name;",
"Export(",
"VRMLExport_Inp7_o1,",
"VRMLExport_Inp8_o1,",
"\"vrml\"",
") [instance: 1, cache: 1];",
"VRMLExport_Format_8_o1[cache: 2] = ",
"Format(",
"\"%s.wrl\",",
"VRMLExport_Inp8_o1,",
"NULL",
") [instance: 8, cache: 1];",
"file_written = VRMLExport_Format_8_o1;",
"}",
NULL
